name: 🚀 Deploy
 
on:
  push:
  pull_request:

env:
  MONGO_URL: ${{secrets.MONGO_URL}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0']

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile      

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-port: 27017
        mongodb-db: db_auth_api
        #mongodb-username: usuario
        #mongodb-password: senha  
              
    - name: Running testing
      run: yarn test

    - name: copy dist via ssh password
      uses: appleboy/scp-action@v0.1.4
      env:
        PORT: 22
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: "dist/*"
        target: "apps_nodejs/trade2023_serviceac"
        debug: true  
        strip_components: 2

    - name: copy file package.json via ssh password
      uses: appleboy/scp-action@v0.1.4
      env:
        PORT: 22
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: package.json
        target: ./apps_nodejs/trade2023_serviceac/
        debug: true   

    - name: Run production scripts
      uses: appleboy/ssh-action@v0.1.4
      env:
        PORT: 22
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
           cd ./apps_nodejs/trade2023_serviceac/
           npm update
           pm2 restart trade2023_serviceac